name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "v5.6.0" ]
  pull_request:
    branches: [ "v5.6.0" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dmcoles/amiga-evo-cicd
      credentials:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    steps: 
      - uses: actions/checkout@v4
      - name: run build
        run: |
           vamos -c /usr/amiga/.vamosrc --cwd esource: -V system:/usr/amiga -V esource:$GITHUB_WORKSPACE make build=release
           vamos -c /usr/amiga/.vamosrc --cwd esource:axSetupTool -V system:/usr/amiga -V esource:$GITHUB_WORKSPACE make build=release

      - name: add build artifacts to publish
        run: |
          apk add lha
          mkdir downloads
          mkdir downloads/utils
          cp $GITHUB_WORKSPACE/express5 downloads
          cp $GITHUB_WORKSPACE/ACP downloads
          cp $GITHUB_WORKSPACE/jsonImport downloads/utils
          cp $GITHUB_WORKSPACE/icon2cfg downloads/utils
          cp $GITHUB_WORKSPACE/qwk downloads/utils
          cp $GITHUB_WORKSPACE/ftn downloads/utils
          cp $GITHUB_WORKSPACE/axSetupTool/axSetupTool downloads/utils 
          cd downloads
          lha a ../amiExpress-nightly${{ github.sha }}.lha *
          ls ../

      - name: Get current date
        id: date
        run: |
          echo "builddate={$(date +'%Y-%m-%d')}" >> $GITHUB_OUTPUT
      - name: Update release files and title
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: dev-build
          name: automated dev build ${{ steps.date.outputs.builddate }}
          files: : amiExpress-nightly${{ github.sha }}.lha

